AllCops:
  Exclude:
  - '*.gemspec'
Layout/HashAlignment:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/RescueModifier:
  Enabled: false
